CREATE TABLE IF NOT EXISTS `schoolregistrationdraft` (
  `code` VARCHAR(191) NOT NULL,
  `step` INT NOT NULL DEFAULT 0,
  `payload` JSON NOT NULL,
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
